# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89ff7a9ca9e7b45bb91511dd6828f206da777384a88ee2c59a5693ef19f6906ca367a5779429209f115669735b59f09ee9fbd8d5c50a594840a1e7a14fcbec8c

test:
  secret_key_base: 26ae9eb0b039ee5f79c941ff889d2280561644c8694590605fbabc302ff995a37384f0242d08c3952e6edfa472effecf9904baaca6aa412cb35c2b1fe6991e4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
